package org.linlinjava.litemall.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.*;
import org.linlinjava.litemall.db.dto.SaleOrderReportDTO;

public interface LitemallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    long countByExample(LitemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByExample(LitemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insert(LitemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int insertSelective(LitemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    List<LitemallOrderGoods> selectByExample(LitemallOrderGoodsExample example);

    List<LitemallOrderGoods> selectOrderGoodsList(LitemallOrderGoods litemallOrderGoods);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallOrderGoods> selectByExampleSelective(@Param("example") LitemallOrderGoodsExample example,
                                                      @Param("selective") LitemallOrderGoods.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    LitemallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id,
                                                   @Param("selective") LitemallOrderGoods.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") LitemallOrderGoods record,
                                 @Param("example") LitemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByExample(@Param("record") LitemallOrderGoods record,
                        @Param("example") LitemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKeySelective(LitemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated Sat Apr 07 10:22:31 CST 2018
     */
    int updateByPrimaryKey(LitemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderGoods selectOneByExample(LitemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table litemall_order_goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallOrderGoods selectOneByExampleSelective(@Param("example") LitemallOrderGoodsExample example,
                                                   @Param("selective") LitemallOrderGoods.Column... selective);

    LitemallTime selectTimeData(@Param("time") String time, @Param("storeId") String storeId, @Param("currentTime") String currentTime);

    String selectMaxServicePeo(@Param("storeId") String storeId);


    void reserveDetail(LitemallReserve litemallReserve);

    void updateOrderGoods(LitemallReserve litemallReserve);


    /**
     * 方法描述  销售订单统计 -- 总数
     *
     * @author huanghaoqi
     * @date 2018年09月27日 14:27:08
     */
    Long saleOrderCount(LitemallReportParam param);

    /**
     * 方法描述  销售订单统计
     *
     * @author huanghaoqi
     * @date 2018年09月27日 14:27:08
     */
    List<SaleOrderReportDTO> saleOrderList(LitemallReportParam param);
}