package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallEarnings;
import org.linlinjava.litemall.db.domain.LitemallEarningsExample;

public interface LitemallEarningsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    long countByExample(LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int deleteByExample(LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int insert(LitemallEarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int insertSelective(LitemallEarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    List<LitemallEarnings> selectByExample(LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallEarnings> selectByExampleSelective(@Param("example") LitemallEarningsExample example, @Param("selective") LitemallEarnings.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    LitemallEarnings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallEarnings selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallEarnings.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") LitemallEarnings record, @Param("example") LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int updateByExample(@Param("record") LitemallEarnings record, @Param("example") LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int updateByPrimaryKeySelective(LitemallEarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    int updateByPrimaryKey(LitemallEarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallEarnings selectOneByExample(LitemallEarningsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallEarnings selectOneByExampleSelective(@Param("example") LitemallEarningsExample example, @Param("selective") LitemallEarnings.Column ... selective);
}