package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallCustomDiscount;
import org.linlinjava.litemall.db.domain.LitemallDiscount;
import org.linlinjava.litemall.db.domain.LitemallDiscountExample;

public interface LitemallDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    long countByExample(LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int deleteByExample(LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int insert(LitemallDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int insertSelective(LitemallDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    List<LitemallDiscount> selectByExample(LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallDiscount> selectByExampleSelective(@Param("example") LitemallDiscountExample example, @Param("selective") LitemallDiscount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    LitemallDiscount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDiscount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallDiscount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") LitemallDiscount record, @Param("example") LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int updateByExample(@Param("record") LitemallDiscount record, @Param("example") LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int updateByPrimaryKeySelective(LitemallDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated Fri May 04 14:11:30 CST 2018
     */
    int updateByPrimaryKey(LitemallDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDiscount selectOneByExample(LitemallDiscountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_discount
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallDiscount selectOneByExampleSelective(@Param("example") LitemallDiscountExample example, @Param("selective") LitemallDiscount.Column ... selective);

	int updateSelective(LitemallCustomDiscount discount);
}