package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;

public class LitemallStorage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.key
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.old_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String oldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.new_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String newName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.type
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.size
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.file_path
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.url
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.modify_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.create_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.create_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.modify_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.deleted
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_storage.img_belongs
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    private String imgBelongs;

    private String screenshotUrl;

    public String getScreenshotUrl() {
        return screenshotUrl;
    }

    public void setScreenshotUrl(String screenshotUrl) {
        this.screenshotUrl = screenshotUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.id
     *
     * @return the value of litemall_storage.id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.id
     *
     * @param id the value for litemall_storage.id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.key
     *
     * @return the value of litemall_storage.key
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.key
     *
     * @param key the value for litemall_storage.key
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.old_name
     *
     * @return the value of litemall_storage.old_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.old_name
     *
     * @param oldName the value for litemall_storage.old_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setOldName(String oldName) {
        this.oldName = oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.new_name
     *
     * @return the value of litemall_storage.new_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getNewName() {
        return newName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.new_name
     *
     * @param newName the value for litemall_storage.new_name
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setNewName(String newName) {
        this.newName = newName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.type
     *
     * @return the value of litemall_storage.type
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.type
     *
     * @param type the value for litemall_storage.type
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.size
     *
     * @return the value of litemall_storage.size
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.size
     *
     * @param size the value for litemall_storage.size
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.file_path
     *
     * @return the value of litemall_storage.file_path
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.file_path
     *
     * @param filePath the value for litemall_storage.file_path
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.url
     *
     * @return the value of litemall_storage.url
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.url
     *
     * @param url the value for litemall_storage.url
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.modify_time
     *
     * @return the value of litemall_storage.modify_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.modify_time
     *
     * @param modifyTime the value for litemall_storage.modify_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.create_user_id
     *
     * @return the value of litemall_storage.create_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.create_user_id
     *
     * @param createUserId the value for litemall_storage.create_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.create_time
     *
     * @return the value of litemall_storage.create_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.create_time
     *
     * @param createTime the value for litemall_storage.create_time
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.modify_user_id
     *
     * @return the value of litemall_storage.modify_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.modify_user_id
     *
     * @param modifyUserId the value for litemall_storage.modify_user_id
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setModifyUserId(String modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.deleted
     *
     * @return the value of litemall_storage.deleted
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.deleted
     *
     * @param deleted the value for litemall_storage.deleted
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_storage.img_belongs
     *
     * @return the value of litemall_storage.img_belongs
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public String getImgBelongs() {
        return imgBelongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_storage.img_belongs
     *
     * @param imgBelongs the value for litemall_storage.img_belongs
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    public void setImgBelongs(String imgBelongs) {
        this.imgBelongs = imgBelongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_storage
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", key=").append(key);
        sb.append(", oldName=").append(oldName);
        sb.append(", newName=").append(newName);
        sb.append(", type=").append(type);
        sb.append(", size=").append(size);
        sb.append(", filePath=").append(filePath);
        sb.append(", url=").append(url);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUserId=").append(modifyUserId);
        sb.append(", deleted=").append(deleted);
        sb.append(", imgBelongs=").append(imgBelongs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_storage
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallStorage other = (LitemallStorage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getOldName() == null ? other.getOldName() == null : this.getOldName().equals(other.getOldName()))
            && (this.getNewName() == null ? other.getNewName() == null : this.getNewName().equals(other.getNewName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getImgBelongs() == null ? other.getImgBelongs() == null : this.getImgBelongs().equals(other.getImgBelongs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_storage
     *
     * @mbg.generated Thu Apr 26 16:54:11 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getOldName() == null) ? 0 : getOldName().hashCode());
        result = prime * result + ((getNewName() == null) ? 0 : getNewName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getImgBelongs() == null) ? 0 : getImgBelongs().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        key("key"),
        oldName("old_name"),
        newName("new_name"),
        type("type"),
        size("size"),
        filePath("file_path"),
        url("url"),
        modifyTime("modify_time"),
        createUserId("create_user_id"),
        createTime("create_time"),
        modifyUserId("modify_user_id"),
        deleted("deleted"),
        imgBelongs("img_belongs");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_storage
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}