package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class LitemallEarnings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.order_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.order_sn
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.order_goods_info_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer orderGoodsInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.order_goods_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer orderGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.operation
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.operation_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private LocalDateTime operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.profit_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer profitUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.profit_money
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private BigDecimal profitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.remark
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.create_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.create_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.modify_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_earnings.modify_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    private Integer modifyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.id
     *
     * @return the value of litemall_earnings.id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.id
     *
     * @param id the value for litemall_earnings.id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.order_id
     *
     * @return the value of litemall_earnings.order_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.order_id
     *
     * @param orderId the value for litemall_earnings.order_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.order_sn
     *
     * @return the value of litemall_earnings.order_sn
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.order_sn
     *
     * @param orderSn the value for litemall_earnings.order_sn
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.order_goods_info_id
     *
     * @return the value of litemall_earnings.order_goods_info_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getOrderGoodsInfoId() {
        return orderGoodsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.order_goods_info_id
     *
     * @param orderGoodsInfoId the value for litemall_earnings.order_goods_info_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOrderGoodsInfoId(Integer orderGoodsInfoId) {
        this.orderGoodsInfoId = orderGoodsInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.order_goods_id
     *
     * @return the value of litemall_earnings.order_goods_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.order_goods_id
     *
     * @param orderGoodsId the value for litemall_earnings.order_goods_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOrderGoodsId(Integer orderGoodsId) {
        this.orderGoodsId = orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.operation
     *
     * @return the value of litemall_earnings.operation
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.operation
     *
     * @param operation the value for litemall_earnings.operation
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.operation_time
     *
     * @return the value of litemall_earnings.operation_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public LocalDateTime getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.operation_time
     *
     * @param operationTime the value for litemall_earnings.operation_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setOperationTime(LocalDateTime operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.profit_user_id
     *
     * @return the value of litemall_earnings.profit_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getProfitUserId() {
        return profitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.profit_user_id
     *
     * @param profitUserId the value for litemall_earnings.profit_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setProfitUserId(Integer profitUserId) {
        this.profitUserId = profitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.profit_money
     *
     * @return the value of litemall_earnings.profit_money
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public BigDecimal getProfitMoney() {
        return profitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.profit_money
     *
     * @param profitMoney the value for litemall_earnings.profit_money
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setProfitMoney(BigDecimal profitMoney) {
        this.profitMoney = profitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.remark
     *
     * @return the value of litemall_earnings.remark
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.remark
     *
     * @param remark the value for litemall_earnings.remark
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.create_time
     *
     * @return the value of litemall_earnings.create_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.create_time
     *
     * @param createTime the value for litemall_earnings.create_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.create_user_id
     *
     * @return the value of litemall_earnings.create_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.create_user_id
     *
     * @param createUserId the value for litemall_earnings.create_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.modify_time
     *
     * @return the value of litemall_earnings.modify_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.modify_time
     *
     * @param modifyTime the value for litemall_earnings.modify_time
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_earnings.modify_user_id
     *
     * @return the value of litemall_earnings.modify_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public Integer getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_earnings.modify_user_id
     *
     * @param modifyUserId the value for litemall_earnings.modify_user_id
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    public void setModifyUserId(Integer modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", orderGoodsInfoId=").append(orderGoodsInfoId);
        sb.append(", orderGoodsId=").append(orderGoodsId);
        sb.append(", operation=").append(operation);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", profitUserId=").append(profitUserId);
        sb.append(", profitMoney=").append(profitMoney);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", modifyUserId=").append(modifyUserId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallEarnings other = (LitemallEarnings) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getOrderGoodsInfoId() == null ? other.getOrderGoodsInfoId() == null : this.getOrderGoodsInfoId().equals(other.getOrderGoodsInfoId()))
            && (this.getOrderGoodsId() == null ? other.getOrderGoodsId() == null : this.getOrderGoodsId().equals(other.getOrderGoodsId()))
            && (this.getOperation() == null ? other.getOperation() == null : this.getOperation().equals(other.getOperation()))
            && (this.getOperationTime() == null ? other.getOperationTime() == null : this.getOperationTime().equals(other.getOperationTime()))
            && (this.getProfitUserId() == null ? other.getProfitUserId() == null : this.getProfitUserId().equals(other.getProfitUserId()))
            && (this.getProfitMoney() == null ? other.getProfitMoney() == null : this.getProfitMoney().equals(other.getProfitMoney()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUserId() == null ? other.getCreateUserId() == null : this.getCreateUserId().equals(other.getCreateUserId()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getModifyUserId() == null ? other.getModifyUserId() == null : this.getModifyUserId().equals(other.getModifyUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_earnings
     *
     * @mbg.generated Fri Jun 22 14:46:52 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getOrderGoodsInfoId() == null) ? 0 : getOrderGoodsInfoId().hashCode());
        result = prime * result + ((getOrderGoodsId() == null) ? 0 : getOrderGoodsId().hashCode());
        result = prime * result + ((getOperation() == null) ? 0 : getOperation().hashCode());
        result = prime * result + ((getOperationTime() == null) ? 0 : getOperationTime().hashCode());
        result = prime * result + ((getProfitUserId() == null) ? 0 : getProfitUserId().hashCode());
        result = prime * result + ((getProfitMoney() == null) ? 0 : getProfitMoney().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUserId() == null) ? 0 : getCreateUserId().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getModifyUserId() == null) ? 0 : getModifyUserId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_earnings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        orderId("order_id"),
        orderSn("order_sn"),
        orderGoodsInfoId("order_goods_info_id"),
        orderGoodsId("order_goods_id"),
        operation("operation"),
        operationTime("operation_time"),
        profitUserId("profit_user_id"),
        profitMoney("profit_money"),
        remark("remark"),
        createTime("create_time"),
        createUserId("create_user_id"),
        modifyTime("modify_time"),
        modifyUserId("modify_user_id");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_earnings
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}